### ISSUE TITLE
> Сhoice у start and end time

### ISSUE THREAD

**Issue by ZUS666** [ZUS666/spot#19]
> Сhoice у start and end time
Что если все таки сделать multichoicefield, типа при заказе натыкиваются временные промежутки
плюс по их количеству считать итоговую стоимость. ту идею с разрывами тоже можно реализовать.
а в модель Location добавить open_time и close_time. По ним валидировать возможность брони. Так можно сделать возможность разных режимов работы для разных локаций. Ну и соответственно в модели Order сделать чойсы начиная от 00:00-00:55, 01:00-01:55 и тд заканчивая 23:00-23:55. Плюс добавить статус заказа LOCK типа если праздничный день например. админ взаранее протыкивает LOCK(ну или сделать это автоматически на определенную дату чтобы руками это не делать(не знаю как это в админке сделать, но ендпоинт точно можно сделать)). Плюс надо тогда ограничить бронь чтобы нельзя было бронить например за пол года или 3 месяца(типа бронь еще не открыта и никто не сможет забронить через 5 лет например).

_Originally posted by @ZUS666 in https://github.com/ZUS666/spot/issues/18#issuecomment-1731865562_

**Comment by Arseny13** [comment]
Мб сначала сделаем полностью рабочий функционал, а потом уже будем пилить доп ?

**Comment by Arseny13** [comment]
Если честно я рил устал менять модель order. Я +- так и думал когда делал мультичойс, но ты сказал что на фронте это не удобно будет + фильтрация будет не удобная. Так что преглаю сначала просто сделать со start и end, а потом уже изменим как фронт попросит.

**Comment by ZUS666** [comment]
Переделывать будет гораздо сложнее а сносить базу если она уже будет набита будет очень не приятно либо писать кастомные миграции в которых лично у меня опыта нет. Я не достоверный источник и высказываю свое мнение и оно точно не всегда правильное. Если считаешь, что кто-то не прав надо отстаивать свое мнение. Про то, что ты уже 100 раз переделывал модель заказов понимаю.

**Comment by Arseny13** [comment]
Если проблема в заполнении бд , то проблем нет. Так как по умолчачию заказов на сайте нет.  Свои мысли я написал в тг.

**Comment by ZUS666** [comment]
а что если оставить и то и другое. типа сделать get_start_time get_end_time. типа чтобы эти поля сами заполнялись из multichoice

**Comment by ZUS666** [comment]
В любом случае удалить поле будет легче

**Comment by ZUS666** [comment]
короче оставить оба варианта multichoice назвать time. После написания фильтров будет понятно, что можно удалить. Валидации новые пока не делать.

**Comment by Arseny13** [comment]
Хорошо.

**Comment by Arseny13** [comment]
Насчет праздников, это последнее что я буду(возможно) делать на этом проекте.

**Comment by Arseny13** [comment]
Все эти фичи, надо делать после полного готового функционала.
