### ISSUE TITLE
Снести модель категорий

### ISSUE THREAD

**Issue by ZUS666** [ZUS666/spot#20]
Предлагаю снести модель категорий. сделать там choicefield и пока сделать только два выбора переговорная или рабочее место.
в любом случае их будет немного и если что можно добавить
отбросим лишние sql  запросы

**Comment by Arseny13** [comment]
Нам от категорий нужны только name, так что идея классная. НО по идеи Equipment должен относится к категории а не к отдельному споту.

**Comment by ZUS666** [comment]
Не согласен насчет equipment. Те же рабочие места могут иметь разное оборудование. Плюс в разных локаций может быть совсем другое оборудование

**Comment by Arseny13** [comment]
Если судить по макету сайти который скинула , Equipment выводится только на старинце локации под именем сategory. На сайте нет отдельных страниц про отдельный спот. Хотя я с тобой согласен что так логично. Но я стороник делать как надо(по макету), а не как хочется.

**Comment by Arseny13** [comment]
И вообще ты тимлид ты и решай.  🙃
