### ISSUE TITLE
кеширование кода подтверждения

### ISSUE THREAD

**Issue by ZUS666** [ZUS666/spot#5]
код подтверждения для разных целей, который отправляется на почту.
есть два кода подтверждения
1. при регистрации для активации.
2. при сбросе пароля.
Кешировать их лучше по разному или одинаково?
cache.set(user.id, confirmation_code, settings.TIMEOUT_CACHED_CODE)
Или для сброса сделать что-то типа
cache.set(f'pw {user.id}', ...)
ну или еще как-то

**Comment by Arseny13** [comment]
Ну мне кажется, это не принципиально. Ну и одна логика == один функционал, не?

**Comment by ZUS666** [comment]
ну сейчас оставил один ключ кеша. плюс после активации пользователя второй раз нельзя получить код активации.
